/* =============================================
   Python 学习追踪器 - Course Data & Structure
   ============================================= */

const COURSE_DATA = {
    overall: {
        totalWeeks: 26,
        totalDays: 130, // 5 days × 26 weeks
        description: "从零掌握Python编程，涵盖语法、数据分析、爬虫、机器学习和办公自动化",
    },

    phases: [
        {
            id: "p1",
            name: "Python 基础语法",
            title: "W1-W8",
            icon: "📝",
            description: "掌握Python编程语言的核心语法，包括变量、数据类型、控制流、函数和面向对象编程。这是所有后续学习的基础。",
            resource: {
                name: "韩顺平 Python零基础入门教程",
                link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                type: "视频课程",
            },
            weeks: {
                w1: {
                    title: "环境搭建与第一个Python程序",
                    subtitle: "安装Python, VSCode, Hello World",
                    days: [
                        {
                            type: "video",
                            title: "安装 Python 3.12 + VSCode",
                            brief: "下载并安装Python 3.12，配置VSCode的Python插件。设置开发环境，确保python和pip命令可用。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "第一个Python程序 — print()",
                            brief: "学习使用print()函数输出文本。编写你的第一个Python程序：打印欢迎信息和简单的数学运算结果。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：编写个人信息程序",
                            brief: "编写一个程序，打印你的名字、年龄、爱好和一句自我介绍。使用多个print()语句。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "输入input()与变量概念",
                            brief: "学习使用input()获取用户输入，理解变量的概念（命名规则、赋值）。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：简单计算器",
                            brief: "编写一个程序，提示用户输入两个数字，然后输出它们的和、差、积。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w2: {
                    title: "数据类型与字符串操作",
                    subtitle: "整数、浮点数、布尔、字符串格式化",
                    days: [
                        {
                            type: "video",
                            title: "数字类型 — int, float, bool",
                            brief: "理解Python中的数字类型，整数和浮点数的运算，布尔值的含义。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "字符串基础与格式化",
                            brief: "字符串的创建、拼接、切片。学习f-string格式化方法，这是Python中最常用的字符串格式化方式。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：个人信息卡片",
                            brief: "使用变量存储个人信息，用f-string格式化输出一个美观的个人信息卡片。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "字符串常用方法",
                            brief: "学习字符串的常用方法：upper(), lower(), split(), join(), replace(), find()等。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：文本处理小工具",
                            brief: "编写一个程序，输入一段英文文本，统计单词数量和字符数量，并输出大写字母版本。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w3: {
                    title: "条件判断",
                    subtitle: "if/elif/else, 逻辑运算符",
                    days: [
                        {
                            type: "video",
                            title: "if-else 条件判断",
                            brief: "学习使用if语句进行条件判断，理解缩进的重要性，else和elif的用法。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "逻辑运算符 — and, or, not",
                            brief: "学习组合条件：使用and、or、not连接多个条件表达式。理解运算符优先级。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：成绩等级判断器",
                            brief: "编写程序，输入分数，输出等级：>=90为A, >=80为B, >=70为C, >=60为D, <60为F。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：简易ATM系统",
                            brief: "模拟一个简单的ATM：输入密码（预设），判断是否正确，正确则显示余额，错误则提示重试（最多3次）。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段复习 — 小项目：猜数字游戏",
                            brief: "综合运用：随机数生成、条件判断、循环。编写一个猜数字游戏，电脑随机生成1-100的数字，玩家有7次机会猜。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "参考示例",
                            checked: false,
                        },
                    ],
                },
                w4: {
                    title: "循环结构",
                    subtitle: "for循环, while循环, break/continue",
                    days: [
                        {
                            type: "video",
                            title: "for循环与range()",
                            brief: "理解for循环的工作原理，range()函数的三种用法：range(n), range(start, end), range(start, end, step)。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "while循环与循环控制",
                            brief: "学习while循环的用法，break跳出循环，continue跳过本次迭代。理解两种循环的使用场景。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：九九乘法表",
                            brief: "使用嵌套for循环打印完整的九九乘法表。注意格式化输出对齐。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：斐波那契数列",
                            brief: "使用while循环打印前20个斐波那契数。理解数列的递推逻辑。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：正倒金字塔图案",
                            brief: "使用嵌套循环打印图案：先打印一个正三角形，再打印一个倒三角形，组合成金字塔图案。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w5: {
                    title: "数据结构：列表与元组",
                    subtitle: "list, tuple, 常用方法",
                    days: [
                        {
                            type: "video",
                            title: "列表的创建与访问",
                            brief: "学习列表的创建、索引访问、切片操作。理解列表是可变的有序序列。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "列表常用方法",
                            brief: "学习append(), insert(), pop(), remove(), sort(), reverse(), len(), count()等列表方法。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：学生成绩管理",
                            brief: "用列表存储5个学生成绩，计算平均分、最高分、最低分，并排序输出。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "元组与列表推导式",
                            brief: "理解元组的不可变特性。学习列表推导式的简洁语法，用于快速生成和操作列表。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：列表推导式实战",
                            brief: "用列表推导式生成1-100中所有偶数的平方，以及1-50中能被3整除的数。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w6: {
                    title: "字典与集合",
                    subtitle: "dict, set, 键值对操作",
                    days: [
                        {
                            type: "video",
                            title: "字典的创建与操作",
                            brief: "学习字典的创建、key-value访问、get()方法、keys()/values()/items()遍历。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：电话簿程序",
                            brief: "创建一个字典存储联系人（姓名:电话号码），实现添加、查询、删除功能。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "集合的概念与操作",
                            brief: "理解集合的特性（无序、唯一），学习集合的并集、交集、差集、对称差集操作。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：去重与统计",
                            brief: "输入一组数字，使用集合去除重复项，统计唯一数字的数量。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段复习 — 综合练习：单词频率统计",
                            brief: "输入一段英文文本，统计每个单词出现的次数，用字典存储并排序输出出现频率最高的10个单词。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w7: {
                    title: "函数",
                    subtitle: "定义函数, 参数, 返回值, 作用域",
                    days: [
                        {
                            type: "video",
                            title: "函数的定义与调用",
                            brief: "学习def关键字定义函数，理解参数和返回值的概念。掌握return和print的区别。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "参数类型 — 位置参数、关键字参数、默认参数",
                            brief: "理解不同类型的参数：位置参数、关键字参数（name=value）、默认参数。学习*args和**kwargs。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：数学工具函数集",
                            brief: "编写多个工具函数：阶乘、判断素数、计算最大公约数、BMI计算器。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "Lambda与变量作用域",
                            brief: "理解局部变量和全局作用域。学习lambda匿名函数的用法和适用场景。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：函数组合应用",
                            brief: "使用map()、filter()、sorted()配合lambda函数处理列表数据。例如：筛选出所有偶数并求平方。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w8: {
                    title: "面向对象 & 文件操作",
                    subtitle: "类与对象, 继承, 文件读写",
                    days: [
                        {
                            type: "video",
                            title: "类与对象基础",
                            brief: "理解面向对象的核心概念：类是蓝图，对象是实例。学习__init__方法和self关键字。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "继承与文件操作",
                            brief: "学习类的继承（父类/子类）。掌握文件操作：open(), read(), write(), with语句。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：学生类设计",
                            brief: "设计一个Student类，包含姓名、学号、成绩属性，以及平均分计算、成绩排序等方法。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：日记本程序",
                            brief: "编写程序，将用户输入的日记内容保存到文本文件中，每次追加一行，带日期时间戳。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "第一阶段大复习",
                            brief: "回顾W1-W8所有内容。尝试独立完成一个小项目，如：简易待办事项管理器（命令行版），包含添加、查看、删除功能。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "回顾视频",
                            checked: false,
                        },
                    ],
                },
            },
        },
        {
            id: "p2",
            name: "数据分析",
            title: "W9-W12",
            icon: "📊",
            description: "学习Python数据分析三大库：NumPy、Pandas和Matplotlib。掌握数据处理、分析和可视化的核心技能。",
            resource: {
                name: "Python数据分析入门+进阶",
                link: "https://www.bilibili.com/video/BV1hx411d7jb",
                type: "视频课程",
            },
            weeks: {
                w9: {
                    title: "NumPy 基础",
                    subtitle: "数组操作, 向量化计算",
                    days: [
                        {
                            type: "video",
                            title: "NumPy安装与数组创建",
                            brief: "安装NumPy库。学习创建数组：np.array(), np.zeros(), np.ones(), np.arange(), np.linspace()。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：数组运算",
                            brief: "创建两个随机数组，进行加减乘除、矩阵乘法、元素级运算。计算数组的均值、标准差。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "数组索引与切片",
                            brief: "学习NumPy数组的高级索引：布尔索引、花式索引、多维数组的切片操作。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：数据筛选",
                            brief: "创建一个100个随机数的数组，筛选出大于均值的所有元素，并计算它们的平均值。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "NumPy综合练习",
                            brief: "模拟一个班级的考试成绩数据（30人×5科），计算每个人的总分和平均分，以及每科的最高分和最低分。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "参考示例",
                            checked: false,
                        },
                    ],
                },
                w10: {
                    title: "Pandas 数据处理",
                    subtitle: "DataFrame, 数据读取, 数据清洗",
                    days: [
                        {
                            type: "video",
                            title: "Pandas DataFrame基础",
                            brief: "学习DataFrame的创建、索引、列操作。理解Series和DataFrame的关系。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "数据读取与清洗",
                            brief: "学习pd.read_csv(), pd.read_excel()读取文件。处理缺失值：dropna(), fillna()。去重：drop_duplicates()。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：CSV数据分析",
                            brief: "下载一个CSV数据集（如电影评分数据），读取后查看前10行，统计每个字段的有效数据量。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "数据筛选与分组",
                            brief: "学习条件筛选：df[df['列']>阈值]。分组聚合：groupby().agg()。排序：sort_values()。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：销售数据分析",
                            brief: "分析一个销售数据集：按月份分组统计总销售额，找出销售最好的产品类别，处理缺失值。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w11: {
                    title: "Matplotlib 数据可视化",
                    subtitle: "折线图, 柱状图, 散点图",
                    days: [
                        {
                            type: "video",
                            title: "Matplotlib基础绘图",
                            brief: "学习plt.plot(), plt.bar(), plt.scatter()的基本用法。设置标题、标签、图例、网格。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：月度趋势图",
                            brief: "用折线图展示12个月的温度变化数据，添加标题、坐标轴标签和网格线。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "高级图表 — 直方图与子图",
                            brief: "学习plt.hist()绘制直方图。使用plt.subplots()创建多子图布局。",
                            link: "https://www.bilibili.com/video/BV1hx411d7jb",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：数据分布分析",
                            brief: "创建一个包含4个子图的图表：考试成绩的直方图、各科平均分柱状图、身高体重散点图、月度趋势折线图。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "数据分析小项目",
                            brief: "选择一个感兴趣的公开数据集（如Kaggle上的电影数据），完成完整的分析流程：读取→清洗→分析→可视化。输出一个包含图表的分析报告。",
                            link: "https://www.bilibili.com/video/BV1tA411H7cQ",
                            linkText: "进阶参考",
                            checked: false,
                        },
                    ],
                },
                w12: {
                    title: "数据分析综合实践",
                    subtitle: "完整分析流程, Seaborn, 实战项目",
                    days: [
                        {
                            type: "video",
                            title: "Seaborn 高级可视化",
                            brief: "学习Seaborn库：热力图、箱线图、配对图。理解Seaborn与Matplotlib的关系和各自优势。",
                            link: "https://www.bilibili.com/video/BV1tA411H7cQ",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：相关性热力图",
                            brief: "使用Seaborn的heatmap()绘制数据相关性矩阵热力图，展示各变量之间的相关性强度。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：数据透视表",
                            brief: "学习pd.pivot_table()创建数据透视表。对数据集进行多维度的交叉分析。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段项目：完整数据分析报告",
                            brief: "选择一个数据集，完成：1)数据加载与探索 2)缺失值处理 3)关键指标分析 4)至少3种图表展示 5)结论总结。",
                            link: "https://www.bilibili.com/video/BV1tA411H7cQ",
                            linkText: "参考案例",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "第二阶段复习",
                            brief: "回顾NumPy、Pandas、Matplotlib核心知识点。整理学习笔记，总结常用命令。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
            },
        },
        {
            id: "p3",
            name: "网络爬虫",
            title: "W13-W16",
            icon: "🕷️",
            description: "学习使用Python从互联网抓取数据。掌握Requests、BeautifulSoup、Selenium等爬虫工具的使用。",
            resource: {
                name: "Python爬虫入门+实战",
                link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                type: "视频课程",
            },
            weeks: {
                w13: {
                    title: "爬虫基础与HTTP协议",
                    subtitle: "Requests, HTML解析, BeautifulSoup",
                    days: [
                        {
                            type: "video",
                            title: "爬虫原理与HTTP请求",
                            brief: "理解爬虫的基本原理：发送HTTP请求→获取HTML→解析数据。安装requests和BeautifulSoup库。",
                            link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：获取网页内容",
                            brief: "使用requests.get()访问Bilibili首页，打印返回的HTML内容。学习查看响应状态码和响应头。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "BeautifulSoup解析HTML",
                            brief: "学习使用BeautifulSoup解析HTML：find(), find_all(), select()方法。理解CSS选择器的语法。",
                            link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：抓取B站热门视频标题",
                            brief: "编写爬虫抓取B站排行榜页面的视频标题和播放量，打印输出。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：保存到CSV",
                            brief: "将抓取的B站视频数据保存到CSV文件中。使用Pandas的to_csv()方法。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w14: {
                    title: "爬虫进阶",
                    subtitle: "代理IP, 请求头, Cookies",
                    days: [
                        {
                            type: "video",
                            title: "反爬虫机制与应对",
                            brief: "了解常见的反爬虫策略：User-Agent检测、IP限制、Cookie验证。学习如何设置请求头。",
                            link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "代理IP与请求频率控制",
                            brief: "学习使用代理IP绕过IP限制。理解time.sleep()控制请求频率的重要性。",
                            link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：模拟登录",
                            brief: "学习使用session对象保持登录状态。模拟登录一个简单的网站并抓取个人页面数据。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：多页数据抓取",
                            brief: "编写爬虫抓取一个多页网站（如豆瓣电影Top250）的全部数据，自动翻页并保存。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段复习",
                            brief: "复习Requests+BeautifulSoup的完整流程。总结爬虫的最佳实践和注意事项。",
                            link: "https://www.bilibili.com/video/BV1Yh411o7Sz",
                            linkText: "参考教程",
                            checked: false,
                        },
                    ],
                },
                w15: {
                    title: "动态页面爬虫",
                    subtitle: "Selenium, 渲染JavaScript, API逆向",
                    days: [
                        {
                            type: "video",
                            title: "Selenium自动化浏览器",
                            brief: "学习Selenium的基本用法：启动浏览器、定位元素、点击、输入、滚动。理解何时需要Selenium。",
                            link: "https://www.bilibili.com/video/BV1Yh411o7Sz",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：Selenium抓取动态页面",
                            brief: "使用Selenium抓取一个需要JavaScript渲染的页面（如微博热搜），提取数据并保存。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "API接口逆向基础",
                            brief: "学习通过浏览器开发者工具(F12)抓取网络请求，找到真实的API接口，直接请求JSON数据。",
                            link: "https://www.bilibili.com/video/BV1Yh411o7Sz",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：API数据抓取",
                            brief: "找到一个网站的API接口，使用requests直接请求JSON数据并解析。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：图片/视频下载爬虫",
                            brief: "编写一个爬虫，抓取网站上的图片或视频资源并保存到本地文件夹。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w16: {
                    title: "爬虫综合项目",
                    subtitle: "完整爬虫项目实战",
                    days: [
                        {
                            type: "video",
                            title: "爬虫项目架构设计",
                            brief: "学习设计一个完整的爬虫项目：项目结构、模块化设计、错误处理、日志记录。",
                            link: "https://www.bilibili.com/video/BV1Yh411o7Sz",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "项目：B站数据爬虫",
                            brief: "设计并实现一个B站热门视频数据爬虫：抓取视频标题、UP主、播放量、弹幕数、发布时间。数据保存到CSV。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "项目：数据清洗与可视化",
                            brief: "将爬虫获取的数据用Pandas清洗分析，用Matplotlib/Seaborn制作可视化图表。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "爬虫项目总结",
                            brief: "整理爬虫项目代码，添加注释和文档。学习如何合法合规地爬取数据，注意robots.txt。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "第三阶段复习",
                            brief: "回顾Requests、BeautifulSoup、Selenium的核心知识点。总结爬虫常见问题和解决方案。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
            },
        },
        {
            id: "p4",
            name: "机器学习",
            title: "W17-W20",
            icon: "🤖",
            description: "学习机器学习的基础概念和常用算法。掌握Scikit-learn库，理解监督学习和无监督学习的核心思想。",
            resource: {
                name: "吴恩达机器学习 / 李宏毅机器学习",
                link: "https://www.bilibili.com/video/BV1dJ411B7gh",
                type: "视频课程",
            },
            weeks: {
                w17: {
                    title: "机器学习基础概念",
                    subtitle: "监督学习, 模型训练与评估",
                    days: [
                        {
                            type: "video",
                            title: "机器学习概述",
                            brief: "理解机器学习的三大类型：监督学习、无监督学习、强化学习。了解机器学习的应用场景。",
                            link: "https://www.bilibili.com/video/BV1dJ411B7gh",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：Scikit-learn环境配置",
                            brief: "安装scikit-learn、joblib库。学习导入数据集：load_iris(), load_boston()等。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "模型训练与评估基础",
                            brief: "学习训练集/测试集的划分（train_test_split）。理解准确率、精确率、召回率的概念。",
                            link: "https://www.bilibili.com/video/BV1dJ411B7gh",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：第一个机器学习模型",
                            brief: "使用K近邻(KNN)算法，在鸢尾花数据集上训练一个分类模型，并评估准确率。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段复习",
                            brief: "回顾机器学习的基本流程：数据准备→特征选择→模型训练→模型评估→模型预测。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "参考课程",
                            checked: false,
                        },
                    ],
                },
                w18: {
                    title: "回归算法",
                    subtitle: "线性回归, 多项式回归, 正则化",
                    days: [
                        {
                            type: "video",
                            title: "线性回归原理与实现",
                            brief: "理解线性回归的数学原理：y = wx + b。使用Scikit-learn实现线性回归模型。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：房价预测",
                            brief: "使用线性回归模型，根据房屋面积预测房价。计算MSE和R²评估指标。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "多项式回归与正则化",
                            brief: "理解过拟合问题，学习多项式回归。掌握岭回归(Ridge)和Lasso回归的正则化方法。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：模型对比",
                            brief: "对比线性回归、多项式回归和岭回归在同一个数据集上的表现，可视化拟合效果。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "回归算法总结",
                            brief: "整理回归算法的适用场景。理解特征缩放(StandardScaler)对回归模型的重要性。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w19: {
                    title: "分类算法",
                    subtitle: "逻辑回归, 决策树, SVM, KNN",
                    days: [
                        {
                            type: "video",
                            title: "逻辑回归与决策树",
                            brief: "学习逻辑回归（用于分类而非回归）。理解决策树的分裂逻辑和剪枝策略。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：鸢尾花分类",
                            brief: "分别使用逻辑回归、决策树、KNN对鸢尾花数据集进行分类，对比它们的准确率和决策边界。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "支持向量机与集成学习",
                            brief: "理解SVM的核心思想（间隔最大化）。学习随机森林和梯度提升（Bagging vs Boosting）。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：手写数字识别",
                            brief: "使用Scikit-learn的digits数据集，训练一个分类器识别手写数字。使用随机森林达到85%+准确率。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "分类算法总结",
                            brief: "对比所有分类算法的优缺点。学习交叉验证(Cross-Validation)评估模型的稳定性。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w20: {
                    title: "机器学习综合项目",
                    subtitle: "完整ML项目流程, 模型调优",
                    days: [
                        {
                            type: "video",
                            title: "模型调优与特征工程",
                            brief: "学习网格搜索(GridSearchCV)调参。理解特征选择、特征提取、特征降维(PCA)的方法。",
                            link: "https://www.bilibili.com/video/BV1JE411g7XF",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "项目： Titanic生存预测",
                            brief: "经典的Titanic数据集项目：数据探索→特征工程→多模型训练→模型调优→提交预测结果。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "项目：保存与加载模型",
                            brief: "学习使用joblib保存训练好的模型，以便后续部署和重新使用。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "机器学习阶段总结",
                            brief: "回顾机器学习核心知识点：回归、分类、模型评估、特征工程。整理算法对比表。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "第四阶段复习",
                            brief: "复习所有ML算法的核心思想。思考如何将ML技能应用到实际工作中。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
            },
        },
        {
            id: "p5",
            name: "办公自动化",
            title: "W21-W22",
            icon: "⚙️",
            description: "学习使用Python自动化处理Excel、Word、PDF和邮件。将繁琐的办公工作交给Python。",
            resource: {
                name: "Python办公自动化入门",
                link: "https://www.bilibili.com/video/BV1y54y1i78U",
                type: "视频课程",
            },
            weeks: {
                w21: {
                    title: "Excel自动化",
                    subtitle: "openpyxl, pandas, 批量处理",
                    days: [
                        {
                            type: "video",
                            title: "openpyxl读取Excel",
                            brief: "学习使用openpyxl读取和写入Excel文件。理解单元格操作、工作表操作。",
                            link: "https://www.bilibili.com/video/BV1y54y1i78U",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：批量处理销售报表",
                            brief: "编写一个程序，读取销售报表Excel，计算每个销售员总业绩，生成汇总报表。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "Excel格式美化与Pandas",
                            brief: "学习用openpyxl设置单元格格式（颜色、字体、边框）。用Pandas快速处理Excel数据。",
                            link: "https://www.bilibili.com/video/BV1y54y1i78U",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：多文件批量合并",
                            brief: "遍历一个文件夹中的所有Excel文件，将它们的Sheet1合并到一个新的汇总表中。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "阶段复习",
                            brief: "复习openpyxl和Pandas的Excel操作。总结日常办公中可以用自动化替代的重复任务。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w22: {
                    title: "Word/PDF/邮件自动化",
                    subtitle: "docx, PyPDF2, 邮件发送",
                    days: [
                        {
                            type: "video",
                            title: "Word文档自动生成",
                            brief: "学习python-docx库：创建文档、添加段落、表格、图片、设置样式。",
                            link: "https://www.bilibili.com/video/BV1y54y1i78U",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：批量生成报告",
                            brief: "根据Excel数据自动生成Word报告，包含标题、表格和结论段落。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "video",
                            title: "PDF操作与邮件自动化",
                            brief: "学习PyPDF2读取和合并PDF。学习smtplib发送带附件的邮件。",
                            link: "https://www.bilibili.com/video/BV1y54y1i78U",
                            linkText: "观看视频教程",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "练习：自动化工作流",
                            brief: "整合：读取Excel数据→生成Word报告→合并PDF→发送邮件给指定收件人。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "办公自动化总结",
                            brief: "回顾所有自动化技能。整理自己的自动化脚本库，准备在实际工作中使用。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
            },
        },
        {
            id: "p6",
            name: "项目实战",
            title: "W23-W26",
            icon: "🚀",
            description: "综合运用前面所学知识，完成2-3个实际项目。从需求分析到代码实现，体验完整的开发流程。",
            resource: {
                name: "综合项目参考",
                link: "https://www.bilibili.com/video/BV12E411A7ZQ",
                type: "参考教程",
            },
            weeks: {
                w23: {
                    title: "项目一：个人数据分析平台",
                    subtitle: "爬虫+数据处理+可视化",
                    days: [
                        {
                            type: "practice",
                            title: "需求分析与设计",
                            brief: "设计一个个人数据分析平台。例如：抓取B站关注UP主的视频数据，分析更新频率、播放趋势。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "数据采集模块",
                            brief: "编写爬虫模块，获取目标数据。处理反爬策略，设置合理的请求间隔。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "数据处理模块",
                            brief: "使用Pandas清洗、整理、分析数据。计算关键指标和趋势。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "可视化与报告生成",
                            brief: "用Matplotlib/Seaborn制作图表，生成包含分析结论的报告文档。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "项目一总结",
                            brief: "完善代码和文档，总结项目经验。思考可以改进的地方。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w24: {
                    title: "项目二：机器学习实战",
                    subtitle: "端到端ML项目",
                    days: [
                        {
                            type: "practice",
                            title: "选择数据集",
                            brief: "从Kaggle或天池选择一个感兴趣的分类或回归数据集。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "EDA探索性数据分析",
                            brief: "对数据进行全面的探索性分析：分布、相关性、异常值检测。可视化关键发现。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "模型训练与调优",
                            brief: "尝试多种算法，使用交叉验证和网格搜索调优。对比模型表现。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "模型部署与报告",
                            brief: "保存最佳模型，编写使用文档。生成项目总结报告。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "项目二总结",
                            brief: "回顾整个ML项目流程。整理模型选择经验和调参心得。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w25: {
                    title: "项目三：办公自动化系统",
                    subtitle: "Excel+Word+邮件集成",
                    days: [
                        {
                            type: "practice",
                            title: "自动化流程设计",
                            brief: "设计一个日常办公自动化方案。例如：每周自动生成周报（从数据库/Excel读取数据→生成Word→发送Email）。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "核心功能实现",
                            brief: "编写数据读取、报告生成、文件处理的核心代码。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "定时任务与错误处理",
                            brief: "学习使用schedule库设置定时任务。添加完善的日志记录和错误处理。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "practice",
                            title: "测试与优化",
                            brief: "测试整个自动化流程。优化性能和用户体验。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "项目三总结",
                            brief: "整理自动化脚本库。编写使用说明文档。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
                w26: {
                    title: "最终复习与未来规划",
                    subtitle: "知识整合, 进阶方向",
                    days: [
                        {
                            type: "review",
                            title: "Python核心知识点回顾",
                            brief: "回顾语法、数据结构、面向对象等基础知识点。查漏补缺。",
                            link: "https://www.bilibili.com/video/BV1FaG1zGEyp",
                            linkText: "基础回顾",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "数据分析技能回顾",
                            brief: "回顾NumPy、Pandas、Matplotlib的核心用法。整理常用代码模板。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "爬虫与ML技能回顾",
                            brief: "回顾爬虫工具和ML算法。整理算法选择指南。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "制定进阶学习计划",
                            brief: "根据个人兴趣，选择后续深入学习方向：Web开发(Django/Flask)、深度学习(PyTorch)、大数据(Hadoop/Spark)等。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                        {
                            type: "review",
                            title: "🎉 恭喜完成26周学习计划！",
                            brief: "回顾整个学习历程，整理笔记和项目代码。你已经从零开始掌握了Python编程的核心技能！继续练习和项目实战才能巩固所学。",
                            link: "",
                            linkText: "",
                            checked: false,
                        },
                    ],
                },
            },
        },
    ],
};
